version: '3'
services:
  sut:
    env_file:
      - .env
    build:
      context: .
      args:
        jdbc_driver_version: ${jdbc_driver_version}
    command: /opt/test_liquibase_mariadb/run_test.sh
    image: liquibase-mariadb:build
    depends_on:
      - db
  db:
    image: db
    container_name: db
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: liquibase
      MYSQL_USER: liquibase
      MYSQL_PASSWORD: liquibase
    ports:
      - 3306:3306
