version: '3'
services:
  sut:
    build: .
    command: /opt/test/run_test.sh
    depends_on:
      - db
  db:
    image: mariadb
    container_name: db
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: liquibase
      MYSQL_USER: liquibase
      MYSQL_PASSWORD: liquibase
    ports:
      - 3306:3306
